### ISSUE TITLE
Missing stack.yaml files for GHC 7.8.4 and 7.10.3

### ISSUE THREAD

**Issue by asr** [agda/agda#2693]
After installing [2.5.3 RC 1](http://www1.eafit.edu.co/asr/tmp-asr/Agda-2.5.2.20170813.tar.gz) I realised that the Stackage `*.yaml` files for GHC 7.8.4 and 7.10.3 are missing. Are we going to include these files for each version supported of GHC? If so, we also should add the corresponding Travis tests.

**Comment by favonia** [comment]
FYI: `lts-2` for GHC 7.8.4 and `lts-6` for GHC 7.10.3.

**Comment by favonia** [comment]
@asr I can help if you are busy working on other things.

**Comment by asr** [comment]
@favonia, I accept your help. Thank you!

You can start from the .yaml files shipped with Agda 2.5.2.

**Comment by asr** [comment]
Please use the stable branch for creating your PR.

**Comment by favonia** [comment]
@asr You are welcome. I want to have 2.5.3 too. Yes I know the stable-2.5 branch.

I found a dependency issue of lts-2/GHC 7.8.4: EdisonCore-1.3.1.1 -> QuickCheck 2.8.2 -> base 4.8.0.0 but the base in lts-2.22 is of version 4.7.0.2. I never tried to overwrite the version of base and I feel it's not worth it even if possible. What would you say? Should we give up testing GHC 7.8.4 with stack?

**Comment by favonia** [comment]
Conflicting versions in Stackage snapshots add some weight to the proposal #2692 I guess.

**Comment by favonia** [comment]
Found an issue about lts-6/GHC 7.10.3: due to https://github.com/commercialhaskell/stack/issues/595 the stack will not install the new cpphs automatically. One workaround is to manually install the newer cpphs and then build Agda.

**Comment by asr** [comment]
It seems I found a build plan for GHC 7.8.4 using

```
$ stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1
``` 
and running

```
$ ARGS="--stack-yaml stack-7.8.4.yaml --system-ghc"
$ stack build $ARGS --no-terminal --test --only-dependencies
```

where `stack-7.8.4.yaml`:
```
flags:
  semigroups:
    bytestring-builder: false
packages:
- '.'
extra-deps:
- binary-0.8.5.1
- boxes-0.1.4
- data-hash-0.2.0.1
- EdisonAPI-1.3.1
- EdisonCore-1.3.1.1
- equivalence-0.3.2
- exceptions-0.8.3
- fail-4.9.0.0
- geniplate-mirror-0.7.4
- gitrev-1.2.0
- haskeline-0.7.2.3
- hashtables-1.2.1.1
- ieee754-0.7.8
- ListLike-4.5.1
- mtl-2.2.1
- monadplus-1.4.2
- murmur-hash-0.1.0.9
- optparse-applicative-0.14.0.0
- primitive-0.6.2.0
- QuickCheck-2.9.2
- regex-tdfa-1.2.2
- regex-tdfa-text-1.0.0.3
- semigroups-0.18.2
- STMonadTrans-0.4.3
- tasty-0.11.2.5
- tasty-silver-3.1.9
- transformers-0.5.4.0
- transformers-compat-0.5.1.4
- unix-compat-0.4.3.1
- vector-0.12.0.1
- void-0.7.1
resolver: lts-2.22
```

**Comment by favonia** [comment]
> It seems I found a build plan for GHC 7.8.4

Sorry for the late report. I also found one by setting flags of QuickCheck. Is there a reason to disable `bytestring-builder`?

**Comment by asr** [comment]
I don't remember the reason for disable `bytestring-builder` (maybe currently it's not necessary).

**Comment by favonia** [comment]
This build plan runs into some wierd recursive dependency when building `gitrev-1.2.0`. Let me try yours. Mine tries hard(er) to use the "minimum" version.

```
resolver: lts-2.22

flags:
  QuickCheck:
    base4: true
    base4point8: false

extra-deps:
- EdisonAPI-1.3.1
- EdisonCore-1.3.1.1
- STMonadTrans-0.4.3
- boxes-0.1.4
- cpphs-1.20.8
- data-hash-0.2.0.1
- equivalence-0.3.2
- fail-4.9.0.0
- geniplate-mirror-0.7.5
- monadplus-1.4.2
- murmur-hash-0.1.0.9
- QuickCheck-2.8.2
- binary-0.7.2.1
- gitrev-1.2.0
- haskeline-0.7.1.3
- ieee754-0.7.8
- mtl-2.2.1
- transformers-compat-0.4.0.4
- transformers-0.4.2.0
- semigroups-0.18
- void-0.7.1
- regex-tdfa-1.2.2
- unix-compat-0.4.3.1
- tasty-silver-3.1.8
- regex-tdfa-text-1.0.0.3
```
