### ISSUE TITLE
Pushes to `stack.yml` cancel existing `test.yml` workflow run

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5389]
Pushing [`c54c453` (#5385)](https://github.com/agda/agda/pull/5385/commits/c54c453008fac30fffdf0e062fe6fb39708a465f) 
1. started the `test.yml` workflow
2. cancelled the running `test.yml` workflow
   This is undesirable, as the work spent in 2. is lost and 1. will not reveal any new insights.

I do not understand why this happens, because `stack.yml` is listed as path to ignore:
https://github.com/agda/agda/blob/4773470ceb0e8671e128109f4728d6416ff93fae/.github/workflows/test.yml#L11

**Comment by andreasabel** [comment]
I suppose this is because `stack.yml` uses the https://github.com/styfle/cancel-workflow-action which will cancel all unfinished workflows.  Maybe this can be made more fine-grained, cancelling only the `stack.yml` workflow?
It has ID 8645, see https://api.github.com/repos/agda/agda/actions/workflows

Or simply put the standard recipe into `stack.yml`:
```
jobs:
  test:
    runs-on: ...

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
```
UPDATE: this standard recipe is what it is there...

So, maybe the basic question is why `test.yml` is triggered by a change to `stack.yml` at all...
