### ISSUE TITLE
Configuration files

### ISSUE THREAD

**Issue by wenkokke** [agda/agda#5553]
I'd like to replace Agda's various home-grown configuration files with a well-known and well-supported _consistent_ format. Currently, Agda uses various different and un- and underdocumented formats:

- `.agda-lib` files
- `~/.agda/libraries`
- `~/.agda/defaults`
- `~/.agda/executables`

My proposal for replacing these is as follows:

1. I'd like to replace the `.agda-lib` files with YAML files using `.agda-lib.yaml`.
2. I'd like to replace the `~/.agda` files with a single `~/.agda/config.yaml` file.

The information contained in these files would be identical, but it would be possible to include extra fields in them. For instance:

```yaml
# filename: plfa.agda-lib.yaml
name: plfa
version: 20.07
depend: [standard-library]
include: [src]
```

```yaml
# filename: ~/.agda/config.yaml
libraries:
- $AGDA_DIR/standard-library/standard-library.agda-lib.yaml
- $AGDA_DIR/agdarsec/agdarsec.agda-lib.yaml
- $AGDA_DIR/schmitty/schmitty.agda-lib.yaml
- $AGDA_DIR/plfa/plfa.agda-lib.yaml
defaults:
- standard-library
executables:
- /usr/local/bin/z3
```

For the foreseable future, these formats would coexist with the current formats, .agda-lib and the various files which live in $AGDA_DIR. If the YAML files are found, Agda uses them. Otherwise, Agda uses the old format, and issues a deprecation warning.

My suggestion would be to use [yaml](https://hackage.haskell.org/package/yaml) with [aeson](https://hackage.haskell.org/package/aeson) to implement these changes, which would give us an incredible simple and readable manner of mapping the contents of these files to Haskell datatypes.

---

### Dhall
I'm aware @andreasabel suggested using Dhall previously, in #4757. I think using a well-known format has accessibility advantages that outweight the coolness of Dhall, even if YAML can get quite hairy if you try to do too much with it.

### Executables
The richer structure of the YAML format opens up the option of extending the `~/.agda/executables` file to an association list which maps Agda postulate names to executables, which would enable a satisfying solution to #5525.
